name: CyberGram Deploy

on:
  push:
    branches: [ main ]


jobs:
  deploy_the_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set-up Node
        uses: actions/setup-node@v3
        with:
          node-version: 21.1.0
      - run: npm ci
      - run: npm run build
      - name: Deploy app to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
            GITHUB_TOKEN: ${{ secrets.CYBERGRAM }}
